#!/bin/sh
set -e # halt script on error

echo "==> Building the site…"
set JEKYLL_ENV=production
bundle exec jekyll build
ls -l


# #!/usr/bin/env bash


# bundle exec jekyll build
# bundle exec htmlproofer ./_site